export type tComment = {
  id: string, // concatenate the review id and then iterate the next value for reply e.g 1-1 means first reply to review with id=1
  img?: string,
  name: string,
  date: current_timestamp,
  content: string,
  star: number, // between 1 and 5 ,the star selected by the user
};
export type tReview = {
  id: number, // set as 1 if this is the first entry for the item, else it should be the next value
  img?: string,
  name: string,
  date: current_timestamp,
  content: string, // message entered by the user in the textarea
  star: number, // number between 1 and 5. the number corresponds to the star selected by the user
  replyComments: tComment[],
};
export type tReport = {
  id: string, // unique random
  message: string, // data inputed in the text area
  date: current_timestamp,
};
export type tMeta = {
  id?: number, // generated by the api, get this from the meta object returned by the api for the selected item. A new entry will be created if its not provided. The existing item will be updated if it is provided
  pid: number, // id of the selected post item. dont confuse this with id above
  review: tReview, // this must be stringified before submission, else the POST request will fail
  report: tReport[],
};
